---
title: "loops"
author: "lbian01"
date: '2022-03-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r 2.1 SPXTTM}
spxOptionCross <- 
  spxOptionCross %>% 
  mutate(diffDate=expiryDate-TradeDate,
         ttm=bizdays(TradeDate,expiryDate,cal = business_calendar)/252) 
  
```


```{r 2.1 SPYTTM}
spyOptionCross <- 
  spyOptionCross %>% 
  mutate(diffDate=expiryDate-TradeDate,
         ttm=bizdays(TradeDate,expiryDate,cal = business_calendar)/252) 
  
```


```{r PUT-CALL}

#Call Option

TESTcall <- spxOptionCross %>% 
  filter(c_p==1) %>% 
  rename(callPrice=price) %>% 
  mutate(Kttm=(ttm/10)+strike) %>% 
  arrange(Kttm) %>% 
  data.frame()

#Put Option

TESTput <- spxOptionCross %>% 
  filter(c_p==0) %>% 
  rename(putPrice=price) %>% 
  mutate(Kttm=(ttm/10)+strike) %>% 
  arrange(Kttm) %>% 
  data.frame()

```

```{r}
callSD <- 
  TESTcall %>% 
  select(expiryDate,strike)


putSD <- 
  TESTput %>% 
  select(expiryDate,strike)

setdiff(callSD,putSD)
```



```{r}
removeCall <- TESTcall %>% 
  filter(expiryDate=='2021-12-17',strike<=200)

xrow=removeCall$X



TESTcall <- 
  TESTcall %>% 
  filter(X!=xrow[1]&X!=xrow[2])

```


```{r}

TESTpaired <- 
  TESTcall %>% 
  left_join(TESTput[,c('Kttm','putPrice')],by='Kttm') %>% 
  select(-c(c_p))

#worning
#underlying only has data till 2020-12-31

```




```{r}

TESTsampleImpliedR <- 
  TESTpaired %>% 
  mutate(putDcall=putPrice-callPrice) %>% 
  select(Kttm,expiryDate,ttm,strike,putDcall,callPrice,putPrice,X) %>% 
  arrange(expiryDate) %>% 
  data.frame()

Dates <- unique(TESTsampleImpliedR$expiryDate)

```



#```{r SPX loop for RandD}
#linear regression



for (i in Dates){

  
lmsample <- 
  TESTsampleImpliedR %>% 
  filter(expiryDate==i)

resIR <- lm(strike ~ x,data = lmsample)

spotUnderlying <- underlying[underlying$TradeDate=="2020-01-10",'SPX']

impliedSPXF <- resIR$coefficients[1]

impliedR <- log(resIR$coefficients[2])/ttm

impliedDividend <- impliedR-log(impliedSPXF/spotUnderlying)/ttm

lmsample <- 
  lmsample %>% 
  mutate(impliedSPXF=resIR$coefficients[1],
         impliedR=log(resIR$coefficients[2])/ttm) %>% 
  mutate(impliedDividend=impliedR-log(impliedSPXF/spotUnderlying)/ttm) 

d=as.Date.numeric(i)

print(paste('for SPX expiry in',d,'we have R=',impliedR,'and Dividend=  ',impliedDividend))

if (i==18278){
  TESTR <- lmsample
} else{ TESTR <- bind_rows(TESTR,lmsample)
    
  }
}


#view(TESTR)


```#



#```{r}
nSteps=1000
call_put=1 #1 for call option, -1 for put option

interestRate=impliedR <- log(resIR$coefficients[2])/ttm

dividendYield=impliedR-log(impliedSPXF/spotUnderlying)/ttm

volatility=volatilitySPX <- underlying[underlying$TradeDate==selectedTradeDate,'stdAnnualSPX']

ttm=TTM <- unique(lmsample$ttm)

spotUnderlying=spotUnderlyingSPX

strike=Strikes <- unique(lmsample$strike)

americanOption=FALSE

deltaT=ttm/nSteps

uCRR=exp(volatility*sqrt(deltaT))

dCRR=exp(-volatility*sqrt(deltaT))

aCRR=exp((interestRate-dividendYield)*(deltaT))

pCRR=(aCRR-dCRR)/(uCRR-dCRR)
```#





###### state price and option price at each node

#```{r 3.1.2 each node}

for (i in nSteps:1){
  optionTemp_1=rep(NA,i)
  statesTemp=rep(NA,i)
  for (j in 1:i){
    statesTemp[j]=spotUnderlying*uCRR^(j-1)*dCRR^(i-1-(j-1))
  }
  
  if (americanOption==TRUE){
    for (j in 1:i){
      optionTemp_1[j]=max(((1-pCRR)*optionTemp[j]+pCRR*optionTemp[j+1])*exp(-interestRate*deltaT),(statesTemp[j]-strike)*call_put)
    }    
  }  else{
    for (j in 1:i){
      optionTemp_1[j]=((1-pCRR)*optionTemp[j]+pCRR*optionTemp[j+1])*exp(-interestRate*deltaT)
    }     
  }
  
  optionTemp=optionTemp_1

}

cat("Option price is: ",optionTemp)

```#





