---
title: "spxOptionCross"
author: "lbian01"
date: "09/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load lib

```{r lib, include=FALSE}
library(tidyverse)
library(moments)
library(tseries)
library(bizdays)
library(magrittr)
```

#################################################################
### put call parity 
#################################################################

```{r ReadData}

spxOptionCross=read.csv("./sampleData/spxOptionData20200110.csv", #check.names=FALSE,
               colClasses=c("numeric","character","character",rep("numeric",3)))

```

```{r TransDate}

spxOptionCross$TradeDate %<>% 
  as.Date("%Y%m%d")

spxOptionCross$expiryDate %<>% 
  as.Date("%Y%m%d")

```


```{r sort&newData}
#spxOptionCross %<>%   arrange(expiryDate)

sort(unique(spxOptionCross$expiryDate))

selectedExpiry <- "2020-06-19"#select from sort?

oneExpiryOptionData <- 
  spxOptionCross %>% 
  filter(expiryDate==selectedExpiry)

```


# calculate business days

```{r calBusiDays}

business_calendar <- 
  create.calendar('my_calendar', 
                  weekdays = c('saturday','sunday'))

ttm=bizdays(oneExpiryOptionData$TradeDate[1],
            oneExpiryOptionData$expiryDate[1], 
            cal = business_calendar)/252

```



```{r cal&Sort Data}
#Call Option
callOptionData <- filter(oneExpiryOptionData,c_p==1)

callOptionData <- callOptionData %>% 
  arrange(strike)

#Put Option
putOptionData <- filter(oneExpiryOptionData,c_p==0)

putOptionData <- putOptionData %>% 
  arrange(strike)

```



```{r group&Plot}

group <- ifelse(oneExpiryOptionData$c_p==1, "Call options", "Put options")

oneExpiryOptionData %>% 
  ggplot(aes(x=strike,y=price,color=group))+
  geom_point()

```


# pair call and put

```{r pair}

pairedOptions <- 
  oneExpiryOptionData %>% 
  distinct(strike) %>% 
  arrange(strike) %>% 
  data.frame() %>%
  left_join(callOptionData[,c('strike','price')],by="strike")# merge by strike

```


```{r rename&merge}

pairedOptions <-
  pairedOptions %>% 
  rename(callPrice=price) %>% 
  left_join(putOptionData[,c('strike','price')],by="strike") %>% 
  rename(putPrice=price)

```


```{r implied&Plot}

pairedOptions %<>% 
  mutate(impliedSPX_Pseudo=callPrice+strike-putPrice)
#plot
ggplot(pairedOptions,aes(x=strike,y=impliedSPX_Pseudo))+
  geom_point(shape = 1)

```

# implied futures, interest rate

```{r sample & regress}

sampleImpliedR <- 
  pairedOptions %>% 
  mutate(x=putPrice-callPrice) %>% 
  select(strike,x) %>% 
  data.frame()

#line regress
resIR=lm(strike ~ x, data = sampleImpliedR)

impliedSPXF=resIR$coefficients[1]

impliedR=log(resIR$coefficients[2])/ttm

```



```{r impliedSPXF&plot}

pairedOptions <- pairedOptions %>% 
  mutate(impliedSPXF=(callPrice-putPrice)*exp(impliedR*ttm)+strike)
#
ggplot(pairedOptions,aes(x=strike,y=impliedSPXF))+
  geom_point()


```


# get the corresponding index level

```{r}

underlying <- read.csv("./sampleData/underlyingSampleData.csv", header=T,as.is = T)

underlying$TradeDate %<>% 
  as.Date("%Y-%m-%d")

spotUnderlying <- underlying[underlying$TradeDate=="2020-01-10",'SPX']

```


# get the corresponding futures price
```{r}

spEminiCross <- read.csv("./sampleData/spxEminiTrade20200110.csv", header=T,as.is = T,check.names=FALSE)

spEminiCross$TradeDate %<>% as.Date("%d/%m/%Y")

spotSPEmini <- spEminiCross[1,'19/06/2020']

```


# implied dividend yield

```{r}

impliedDividend <- impliedR-log(impliedSPXF/spotUnderlying)/ttm
```


# implied index level
```{r}

pairedOptions <- 
  pairedOptions %>% 
  mutate(impliedSPX=
           (callPrice-putPrice+strike*exp(-impliedR*ttm))
         *exp(impliedDividend*ttm)
         )
#Plot
ggplot(pairedOptions,aes(x=strike,y=impliedSPX))+
  geom_point(shape=1)

impliedSPX <- mean(pairedOptions$impliedSPX)
```

#################################################################


#################################################################
### Option bounds
#################################################################
#call options


```{r}

callOptionData <- 
  callOptionData %>% 
  mutate(upperBound=spotUnderlying,
         lowerBound=impliedSPX*exp(-impliedDividend*ttm)-strike*exp(-impliedR*ttm))

callOptionData$lowerBound[callOptionData$lowerBound<0]=0

```


```{r PlotCall}
callOptionData %>% 
  ggplot(aes(x=strike))+
  ylim(0,spotUnderlying*1.2)+
  geom_point(aes(y=price),shape=1)+
  geom_line(aes(y=upperBound,colour="upperBound"))+
  geom_line(aes(y=lowerBound,colour="lowerBound"))
```


#put option

```{r}
putOptionData <- 
  putOptionData %>% 
  mutate(upperBound=strike*exp(-impliedR*ttm),
         lowerBound=strike*exp(-impliedR*ttm)-spotUnderlying*exp(-impliedDividend*ttm))

putOptionData$lowerBound[putOptionData$lowerBound<0]=0
```


```{r PlotPut}
putOptionData %>% 
  ggplot(aes(x=strike))+
  ylim(0,spotUnderlying*1.2)+
  geom_point(aes(y=price),shape=1)+
  geom_line(aes(y=upperBound,colour="upperBound"))+
  geom_line(aes(y=lowerBound,colour="lowerBound"))



```



