knitr::purl("SPXtree.rmd")
knitr::purl("preSPXtree.rmd")
knitr::purl("q6spx.rmd")
knitr::purl("GBM.rmd")
knitr::purl("BSMloop.rmd")
knitr::purl("MClnS.rmd")
knitr::purl("computerPractice 1&2&3 ReOrg.rmd")
