---
title: "S&P 500 Emini"
author: "lbian01"
date: "09/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load lib

```{r lib, include=FALSE}
library(tidyverse)
library(tidyquant)
library(moments)
library(tseries)
library(bizdays)
```

# read the S&P 500 Emini cross section data on 20200110
spEminiCross=read.csv("./sampleData/spxEminiTrade20200110.csv", header=T,as.is = T,check.names=FALSE)
spEminiCross$TradeDate=as.Date(spEminiCross$TradeDate, format = "%d/%m/%Y")

# load lib
```{r loadData}
spEminiCross=read.csv("./sampleData/spxEminiTrade20200110.csv", header=T,as.is = T,check.names=FALSE)

spEminiCross$TradeDate <- 
  spEminiCross$TradeDate %>%
  as.Date("%d/%m/%Y")

```




```{r}
spotIndex=underlying[underlying$TradeDate==spEminiCross$TradeDate,'SPX']

deliveryDate=as.Date(colnames(spEminiCross)[2:length(colnames(spEminiCross))], format = "%d/%m/%Y") 


```



```{r cal businessDays}
# calculate business days

business_calendar <- create.calendar('my_calendar', weekdays = c('saturday','sunday'))

ttm=bizdays(spEminiCross$TradeDate, deliveryDate, cal = business_calendar)/252


```


```{r CostOfCarry}
# cost of carry
log(
  spEminiCross[,2:length(spEminiCross)]/
    spotIndex)/
  ttm

```
# Line 85
