---
title: "Untitled"
author: "lbian01"
date: "09/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load lib

```{r lib, include=FALSE}

library(tidyverse)
library(moments)
library(tseries)
library(bizdays)
```


###################################################################
# read the S&P 500 Emini time series data 

```{r ReadData}
spEminiTS=read.csv("./sampleData/spxEminiEx20200619.csv", header=T,as.is = T,check.names=FALSE)

spEminiTS$TradeDate %<>% 
  as.Date("%d/%m/%Y")

```





```{r}
#merge SPX to TS by Date
spEminiTS=merge(x=spEminiTS,y=underlying[c('TradeDate','SPX')],by="TradeDate",all.x=TRUE)

```


```{r mutate new Basis cols}
spEminiTS <- 
  spEminiTS %>% 
  mutate(Basis=spEminiTS$`19/06/2020`-SPX,
         BasisP=SPX/spEminiTS$`19/06/2020`-1)

```


```{r plot}
spEminiTS %>% 
  ggplot(aes(x=TradeDate,y=Basis))+
  geom_line(colour="#ff0000")

spEminiTS %>% 
  ggplot(aes(x=TradeDate,y=BasisP))+
  geom_line()


```
# line 96
